/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCronRequest,
  CreateCronResponse,
  CronSchedule,
  ErrorBody,
  ListCronsResponse,
} from '../models/index';
import {
    CreateCronRequestFromJSON,
    CreateCronRequestToJSON,
    CreateCronResponseFromJSON,
    CreateCronResponseToJSON,
    CronScheduleFromJSON,
    CronScheduleToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListCronsResponseFromJSON,
    ListCronsResponseToJSON,
} from '../models/index';

export interface CreateCronOperationRequest {
    createCronRequest: CreateCronRequest;
}

export interface DeleteCronRequest {
    id: string;
}

export interface GetCronRequest {
    id: string;
}

export interface ListCronsRequest {
    status?: string;
    queue?: string;
    limit?: number;
    offset?: number;
    orderBy?: string;
    includeTotal?: boolean;
    cursor?: string;
}

export interface PauseCronRequest {
    id: string;
}

export interface ResumeCronRequest {
    id: string;
}

/**
 * CronApi - interface
 * 
 * @export
 * @interface CronApiInterface
 */
export interface CronApiInterface {
    /**
     * 
     * @param {CreateCronRequest} createCronRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CronApiInterface
     */
    createCronRaw(requestParameters: CreateCronOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCronResponse>>;

    /**
     */
    createCron(requestParameters: CreateCronOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCronResponse>;

    /**
     * 
     * @param {string} id Cron schedule id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CronApiInterface
     */
    deleteCronRaw(requestParameters: DeleteCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteCron(requestParameters: DeleteCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id Cron schedule id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CronApiInterface
     */
    getCronRaw(requestParameters: GetCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CronSchedule>>;

    /**
     */
    getCron(requestParameters: GetCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CronSchedule>;

    /**
     * 
     * @param {string} [status] Filter by status (e.g. &#x60;pending&#x60;, &#x60;completed&#x60;).
     * @param {string} [queue] Filter by queue name (jobs only).
     * @param {number} [limit] Page size, 1..&#x3D;100 (default 50).
     * @param {number} [offset] Number of records to skip (default 0).
     * @param {string} [orderBy] &#x60;created_at ASC&#x60; or &#x60;created_at DESC&#x60; (default DESC).
     * @param {boolean} [includeTotal] Include the exact &#x60;total&#x60; count in the response (default false; the count is an extra full scan over the filtered set).
     * @param {string} [cursor] Opaque keyset cursor from a previous page\&#39;s &#x60;next_cursor&#x60;. When set, &#x60;offset&#x60; is ignored and listing continues where that page ended.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CronApiInterface
     */
    listCronsRaw(requestParameters: ListCronsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCronsResponse>>;

    /**
     */
    listCrons(requestParameters: ListCronsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCronsResponse>;

    /**
     * 
     * @param {string} id Cron schedule id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CronApiInterface
     */
    pauseCronRaw(requestParameters: PauseCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    pauseCron(requestParameters: PauseCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id Cron schedule id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CronApiInterface
     */
    resumeCronRaw(requestParameters: ResumeCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    resumeCron(requestParameters: ResumeCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class CronApi extends runtime.BaseAPI implements CronApiInterface {

    /**
     */
    async createCronRaw(requestParameters: CreateCronOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCronResponse>> {
        if (requestParameters['createCronRequest'] == null) {
            throw new runtime.RequiredError(
                'createCronRequest',
                'Required parameter "createCronRequest" was null or undefined when calling createCron().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/cron`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCronRequestToJSON(requestParameters['createCronRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateCronResponseFromJSON(jsonValue));
    }

    /**
     */
    async createCron(requestParameters: CreateCronOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCronResponse> {
        const response = await this.createCronRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteCronRaw(requestParameters: DeleteCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCron().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/cron/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteCron(requestParameters: DeleteCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCronRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getCronRaw(requestParameters: GetCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CronSchedule>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCron().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/cron/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CronScheduleFromJSON(jsonValue));
    }

    /**
     */
    async getCron(requestParameters: GetCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CronSchedule> {
        const response = await this.getCronRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listCronsRaw(requestParameters: ListCronsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCronsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['queue'] != null) {
            queryParameters['queue'] = requestParameters['queue'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/cron`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCronsResponseFromJSON(jsonValue));
    }

    /**
     */
    async listCrons(requestParameters: ListCronsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCronsResponse> {
        const response = await this.listCronsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async pauseCronRaw(requestParameters: PauseCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pauseCron().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/cron/{id}/pause`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async pauseCron(requestParameters: PauseCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pauseCronRaw(requestParameters, initOverrides);
    }

    /**
     */
    async resumeCronRaw(requestParameters: ResumeCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resumeCron().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/cron/{id}/resume`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async resumeCron(requestParameters: ResumeCronRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resumeCronRaw(requestParameters, initOverrides);
    }

}
