/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeadLetter,
  ErrorBody,
  ListDeadLettersResponse,
  ReplayDeadLetterResponse,
} from '../models/index';
import {
    DeadLetterFromJSON,
    DeadLetterToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListDeadLettersResponseFromJSON,
    ListDeadLettersResponseToJSON,
    ReplayDeadLetterResponseFromJSON,
    ReplayDeadLetterResponseToJSON,
} from '../models/index';

export interface GetDeadLetterRequest {
    id: number;
}

export interface ListDeadLettersRequest {
    status?: string;
    queue?: string;
    limit?: number;
    offset?: number;
    orderBy?: string;
    includeTotal?: boolean;
    cursor?: string;
    createdAfter?: Date;
    createdBefore?: Date;
}

export interface ReplayDeadLetterRequest {
    id: number;
}

/**
 * DlqApi - interface
 * 
 * @export
 * @interface DlqApiInterface
 */
export interface DlqApiInterface {
    /**
     * 
     * @param {number} id Dead letter id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DlqApiInterface
     */
    getDeadLetterRaw(requestParameters: GetDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeadLetter>>;

    /**
     */
    getDeadLetter(requestParameters: GetDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeadLetter>;

    /**
     * 
     * @param {string} [status] Filter by status (e.g. &#x60;pending&#x60;, &#x60;completed&#x60;).
     * @param {string} [queue] Filter by queue name (jobs only).
     * @param {number} [limit] Page size, 1..&#x3D;100 (default 50).
     * @param {number} [offset] Number of records to skip (default 0).
     * @param {string} [orderBy] &#x60;created_at ASC&#x60; or &#x60;created_at DESC&#x60; (default DESC).
     * @param {boolean} [includeTotal] Include the exact &#x60;total&#x60; count in the response (default false; the count is an extra full scan over the filtered set).
     * @param {string} [cursor] Opaque keyset cursor from a previous page\&#39;s &#x60;next_cursor&#x60;. When set, &#x60;offset&#x60; is ignored and listing continues where that page ended.
     * @param {Date} [createdAfter] Only rows created at or after this instant (RFC 3339, inclusive). With &#x60;created_before&#x60; this forms the half-open range &#x60;[after, before)&#x60; — the natural shape for walking history period by period.
     * @param {Date} [createdBefore] Only rows created strictly before this instant (RFC 3339, exclusive).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DlqApiInterface
     */
    listDeadLettersRaw(requestParameters: ListDeadLettersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDeadLettersResponse>>;

    /**
     */
    listDeadLetters(requestParameters: ListDeadLettersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDeadLettersResponse>;

    /**
     * 
     * @param {number} id Dead letter id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DlqApiInterface
     */
    replayDeadLetterRaw(requestParameters: ReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReplayDeadLetterResponse>>;

    /**
     */
    replayDeadLetter(requestParameters: ReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReplayDeadLetterResponse>;

}

/**
 * 
 */
export class DlqApi extends runtime.BaseAPI implements DlqApiInterface {

    /**
     */
    async getDeadLetterRaw(requestParameters: GetDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeadLetter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDeadLetter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/dlq/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeadLetterFromJSON(jsonValue));
    }

    /**
     */
    async getDeadLetter(requestParameters: GetDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeadLetter> {
        const response = await this.getDeadLetterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listDeadLettersRaw(requestParameters: ListDeadLettersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDeadLettersResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['queue'] != null) {
            queryParameters['queue'] = requestParameters['queue'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['createdAfter'] != null) {
            queryParameters['created_after'] = (requestParameters['createdAfter'] as any).toISOString();
        }

        if (requestParameters['createdBefore'] != null) {
            queryParameters['created_before'] = (requestParameters['createdBefore'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/dlq`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDeadLettersResponseFromJSON(jsonValue));
    }

    /**
     */
    async listDeadLetters(requestParameters: ListDeadLettersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDeadLettersResponse> {
        const response = await this.listDeadLettersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async replayDeadLetterRaw(requestParameters: ReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReplayDeadLetterResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling replayDeadLetter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/dlq/{id}/replay`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReplayDeadLetterResponseFromJSON(jsonValue));
    }

    /**
     */
    async replayDeadLetter(requestParameters: ReplayDeadLetterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReplayDeadLetterResponse> {
        const response = await this.replayDeadLetterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
