/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWorkflowRequest,
  CreateWorkflowResponse,
  ErrorBody,
  ListWorkflowsResponse,
  Workflow,
  WorkflowDiagramResponse,
} from '../models/index';
import {
    CreateWorkflowRequestFromJSON,
    CreateWorkflowRequestToJSON,
    CreateWorkflowResponseFromJSON,
    CreateWorkflowResponseToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListWorkflowsResponseFromJSON,
    ListWorkflowsResponseToJSON,
    WorkflowFromJSON,
    WorkflowToJSON,
    WorkflowDiagramResponseFromJSON,
    WorkflowDiagramResponseToJSON,
} from '../models/index';

export interface CancelWorkflowRequest {
    id: string;
}

export interface CreateWorkflowOperationRequest {
    createWorkflowRequest: CreateWorkflowRequest;
}

export interface GetWorkflowRequest {
    id: string;
}

export interface GetWorkflowDiagramRequest {
    id: string;
}

export interface ListWorkflowsRequest {
    status?: string;
    queue?: string;
    limit?: number;
    offset?: number;
    orderBy?: string;
    includeTotal?: boolean;
    cursor?: string;
}

/**
 * WorkflowsApi - interface
 * 
 * @export
 * @interface WorkflowsApiInterface
 */
export interface WorkflowsApiInterface {
    /**
     * 
     * @param {string} id Workflow id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowsApiInterface
     */
    cancelWorkflowRaw(requestParameters: CancelWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    cancelWorkflow(requestParameters: CancelWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {CreateWorkflowRequest} createWorkflowRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowsApiInterface
     */
    createWorkflowRaw(requestParameters: CreateWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkflowResponse>>;

    /**
     */
    createWorkflow(requestParameters: CreateWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkflowResponse>;

    /**
     * 
     * @param {string} id Workflow id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowsApiInterface
     */
    getWorkflowRaw(requestParameters: GetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Workflow>>;

    /**
     */
    getWorkflow(requestParameters: GetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Workflow>;

    /**
     * 
     * @param {string} id Workflow id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowsApiInterface
     */
    getWorkflowDiagramRaw(requestParameters: GetWorkflowDiagramRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDiagramResponse>>;

    /**
     */
    getWorkflowDiagram(requestParameters: GetWorkflowDiagramRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDiagramResponse>;

    /**
     * 
     * @param {string} [status] Filter by status (e.g. &#x60;pending&#x60;, &#x60;completed&#x60;).
     * @param {string} [queue] Filter by queue name (jobs only).
     * @param {number} [limit] Page size, 1..&#x3D;100 (default 50).
     * @param {number} [offset] Number of records to skip (default 0).
     * @param {string} [orderBy] &#x60;created_at ASC&#x60; or &#x60;created_at DESC&#x60; (default DESC).
     * @param {boolean} [includeTotal] Include the exact &#x60;total&#x60; count in the response (default false; the count is an extra full scan over the filtered set).
     * @param {string} [cursor] Opaque keyset cursor from a previous page\&#39;s &#x60;next_cursor&#x60;. When set, &#x60;offset&#x60; is ignored and listing continues where that page ended.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowsApiInterface
     */
    listWorkflowsRaw(requestParameters: ListWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkflowsResponse>>;

    /**
     */
    listWorkflows(requestParameters: ListWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkflowsResponse>;

}

/**
 * 
 */
export class WorkflowsApi extends runtime.BaseAPI implements WorkflowsApiInterface {

    /**
     */
    async cancelWorkflowRaw(requestParameters: CancelWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/workflows/{id}/cancel`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async cancelWorkflow(requestParameters: CancelWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelWorkflowRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createWorkflowRaw(requestParameters: CreateWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkflowResponse>> {
        if (requestParameters['createWorkflowRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkflowRequest',
                'Required parameter "createWorkflowRequest" was null or undefined when calling createWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/workflows`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkflowRequestToJSON(requestParameters['createWorkflowRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWorkflowResponseFromJSON(jsonValue));
    }

    /**
     */
    async createWorkflow(requestParameters: CreateWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkflowResponse> {
        const response = await this.createWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getWorkflowRaw(requestParameters: GetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Workflow>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/workflows/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowFromJSON(jsonValue));
    }

    /**
     */
    async getWorkflow(requestParameters: GetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Workflow> {
        const response = await this.getWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getWorkflowDiagramRaw(requestParameters: GetWorkflowDiagramRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowDiagramResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflowDiagram().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/workflows/{id}/diagram`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowDiagramResponseFromJSON(jsonValue));
    }

    /**
     */
    async getWorkflowDiagram(requestParameters: GetWorkflowDiagramRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowDiagramResponse> {
        const response = await this.getWorkflowDiagramRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listWorkflowsRaw(requestParameters: ListWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkflowsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['queue'] != null) {
            queryParameters['queue'] = requestParameters['queue'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/workflows`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWorkflowsResponseFromJSON(jsonValue));
    }

    /**
     */
    async listWorkflows(requestParameters: ListWorkflowsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkflowsResponse> {
        const response = await this.listWorkflowsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
