/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompleteJobRequest,
  ErrorBody,
  FailJobRequest,
  HeartbeatRequest,
  HeartbeatResponse,
  LeaseJobsRequest,
  LeaseJobsResponse,
} from '../models/index';
import {
    CompleteJobRequestFromJSON,
    CompleteJobRequestToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    FailJobRequestFromJSON,
    FailJobRequestToJSON,
    HeartbeatRequestFromJSON,
    HeartbeatRequestToJSON,
    HeartbeatResponseFromJSON,
    HeartbeatResponseToJSON,
    LeaseJobsRequestFromJSON,
    LeaseJobsRequestToJSON,
    LeaseJobsResponseFromJSON,
    LeaseJobsResponseToJSON,
} from '../models/index';

export interface CompleteJobOperationRequest {
    id: string;
    completeJobRequest: CompleteJobRequest;
}

export interface FailJobOperationRequest {
    id: string;
    failJobRequest: FailJobRequest;
}

export interface HeartbeatJobRequest {
    id: string;
    heartbeatRequest: HeartbeatRequest;
}

export interface LeaseJobsOperationRequest {
    queue: string;
    leaseJobsRequest: LeaseJobsRequest;
}

/**
 * WorkerApi - interface
 * 
 * @export
 * @interface WorkerApiInterface
 */
export interface WorkerApiInterface {
    /**
     * 
     * @param {string} id Job id
     * @param {CompleteJobRequest} completeJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkerApiInterface
     */
    completeJobRaw(requestParameters: CompleteJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    completeJob(requestParameters: CompleteJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id Job id
     * @param {FailJobRequest} failJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkerApiInterface
     */
    failJobRaw(requestParameters: FailJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    failJob(requestParameters: FailJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} id Job id
     * @param {HeartbeatRequest} heartbeatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkerApiInterface
     */
    heartbeatJobRaw(requestParameters: HeartbeatJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HeartbeatResponse>>;

    /**
     */
    heartbeatJob(requestParameters: HeartbeatJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HeartbeatResponse>;

    /**
     * 
     * @param {string} queue Queue to lease from
     * @param {LeaseJobsRequest} leaseJobsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkerApiInterface
     */
    leaseJobsRaw(requestParameters: LeaseJobsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaseJobsResponse>>;

    /**
     */
    leaseJobs(requestParameters: LeaseJobsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaseJobsResponse>;

}

/**
 * 
 */
export class WorkerApi extends runtime.BaseAPI implements WorkerApiInterface {

    /**
     */
    async completeJobRaw(requestParameters: CompleteJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling completeJob().'
            );
        }

        if (requestParameters['completeJobRequest'] == null) {
            throw new runtime.RequiredError(
                'completeJobRequest',
                'Required parameter "completeJobRequest" was null or undefined when calling completeJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs/{id}/complete`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompleteJobRequestToJSON(requestParameters['completeJobRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async completeJob(requestParameters: CompleteJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.completeJobRaw(requestParameters, initOverrides);
    }

    /**
     */
    async failJobRaw(requestParameters: FailJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling failJob().'
            );
        }

        if (requestParameters['failJobRequest'] == null) {
            throw new runtime.RequiredError(
                'failJobRequest',
                'Required parameter "failJobRequest" was null or undefined when calling failJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs/{id}/fail`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FailJobRequestToJSON(requestParameters['failJobRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async failJob(requestParameters: FailJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.failJobRaw(requestParameters, initOverrides);
    }

    /**
     */
    async heartbeatJobRaw(requestParameters: HeartbeatJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HeartbeatResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling heartbeatJob().'
            );
        }

        if (requestParameters['heartbeatRequest'] == null) {
            throw new runtime.RequiredError(
                'heartbeatRequest',
                'Required parameter "heartbeatRequest" was null or undefined when calling heartbeatJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs/{id}/heartbeat`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HeartbeatRequestToJSON(requestParameters['heartbeatRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HeartbeatResponseFromJSON(jsonValue));
    }

    /**
     */
    async heartbeatJob(requestParameters: HeartbeatJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HeartbeatResponse> {
        const response = await this.heartbeatJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async leaseJobsRaw(requestParameters: LeaseJobsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeaseJobsResponse>> {
        if (requestParameters['queue'] == null) {
            throw new runtime.RequiredError(
                'queue',
                'Required parameter "queue" was null or undefined when calling leaseJobs().'
            );
        }

        if (requestParameters['leaseJobsRequest'] == null) {
            throw new runtime.RequiredError(
                'leaseJobsRequest',
                'Required parameter "leaseJobsRequest" was null or undefined when calling leaseJobs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/queues/{queue}/lease`.replace(`{${"queue"}}`, encodeURIComponent(String(requestParameters['queue']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LeaseJobsRequestToJSON(requestParameters['leaseJobsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeaseJobsResponseFromJSON(jsonValue));
    }

    /**
     */
    async leaseJobs(requestParameters: LeaseJobsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeaseJobsResponse> {
        const response = await this.leaseJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
