/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How retry delays grow between attempts.
 * @export
 */
export const BackoffStrategy = {
    Fixed: 'fixed',
    Linear: 'linear',
    Exponential: 'exponential'
} as const;
export type BackoffStrategy = typeof BackoffStrategy[keyof typeof BackoffStrategy];


export function instanceOfBackoffStrategy(value: any): boolean {
    for (const key in BackoffStrategy) {
        if (Object.prototype.hasOwnProperty.call(BackoffStrategy, key)) {
            if (BackoffStrategy[key as keyof typeof BackoffStrategy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BackoffStrategyFromJSON(json: any): BackoffStrategy {
    return BackoffStrategyFromJSONTyped(json, false);
}

export function BackoffStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackoffStrategy {
    return json as BackoffStrategy;
}

export function BackoffStrategyToJSON(value?: BackoffStrategy | null): any {
    return value as any;
}

export function BackoffStrategyToJSONTyped(value: any, ignoreDiscriminator: boolean): BackoffStrategy {
    return value as BackoffStrategy;
}

