/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for `POST /api/v1/jobs/{id}/complete`.
 * @export
 * @interface CompleteJobRequest
 */
export interface CompleteJobRequest {
    /**
     * The lease token returned by the lease call.
     * @type {string}
     * @memberof CompleteJobRequest
     */
    lease_token: string;
    /**
     * Handler result, recorded on the job and merged into workflow context.
     * @type {{ [key: string]: any; }}
     * @memberof CompleteJobRequest
     */
    result?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CompleteJobRequest interface.
 */
export function instanceOfCompleteJobRequest(value: object): value is CompleteJobRequest {
    if (!('lease_token' in value) || value['lease_token'] === undefined) return false;
    return true;
}

export function CompleteJobRequestFromJSON(json: any): CompleteJobRequest {
    return CompleteJobRequestFromJSONTyped(json, false);
}

export function CompleteJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lease_token': json['lease_token'],
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function CompleteJobRequestToJSON(json: any): CompleteJobRequest {
    return CompleteJobRequestToJSONTyped(json, false);
}

export function CompleteJobRequestToJSONTyped(value?: CompleteJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lease_token': value['lease_token'],
        'result': value['result'],
    };
}

