/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateJobRequest } from './CreateJobRequest';
import {
    CreateJobRequestFromJSON,
    CreateJobRequestFromJSONTyped,
    CreateJobRequestToJSON,
    CreateJobRequestToJSONTyped,
} from './CreateJobRequest';

/**
 * 
 * @export
 * @interface CreateBatchJobsRequest
 */
export interface CreateBatchJobsRequest {
    /**
     * 
     * @type {Array<CreateJobRequest>}
     * @memberof CreateBatchJobsRequest
     */
    jobs: Array<CreateJobRequest>;
}

/**
 * Check if a given object implements the CreateBatchJobsRequest interface.
 */
export function instanceOfCreateBatchJobsRequest(value: object): value is CreateBatchJobsRequest {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    return true;
}

export function CreateBatchJobsRequestFromJSON(json: any): CreateBatchJobsRequest {
    return CreateBatchJobsRequestFromJSONTyped(json, false);
}

export function CreateBatchJobsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBatchJobsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(CreateJobRequestFromJSON)),
    };
}

export function CreateBatchJobsRequestToJSON(json: any): CreateBatchJobsRequest {
    return CreateBatchJobsRequestToJSONTyped(json, false);
}

export function CreateBatchJobsRequestToJSONTyped(value?: CreateBatchJobsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': ((value['jobs'] as Array<any>).map(CreateJobRequestToJSON)),
    };
}

