/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCronResponse
 */
export interface CreateCronResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCronResponse
     */
    cron_id: string;
}

/**
 * Check if a given object implements the CreateCronResponse interface.
 */
export function instanceOfCreateCronResponse(value: object): value is CreateCronResponse {
    if (!('cron_id' in value) || value['cron_id'] === undefined) return false;
    return true;
}

export function CreateCronResponseFromJSON(json: any): CreateCronResponse {
    return CreateCronResponseFromJSONTyped(json, false);
}

export function CreateCronResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCronResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cron_id': json['cron_id'],
    };
}

export function CreateCronResponseToJSON(json: any): CreateCronResponse {
    return CreateCronResponseToJSONTyped(json, false);
}

export function CreateCronResponseToJSONTyped(value?: CreateCronResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cron_id': value['cron_id'],
    };
}

