/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateJobResponse
 */
export interface CreateJobResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateJobResponse
     */
    job_id: string;
}

/**
 * Check if a given object implements the CreateJobResponse interface.
 */
export function instanceOfCreateJobResponse(value: object): value is CreateJobResponse {
    if (!('job_id' in value) || value['job_id'] === undefined) return false;
    return true;
}

export function CreateJobResponseFromJSON(json: any): CreateJobResponse {
    return CreateJobResponseFromJSONTyped(json, false);
}

export function CreateJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'job_id': json['job_id'],
    };
}

export function CreateJobResponseToJSON(json: any): CreateJobResponse {
    return CreateJobResponseToJSONTyped(json, false);
}

export function CreateJobResponseToJSONTyped(value?: CreateJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['job_id'],
    };
}

