/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBatchJobsResponse
 */
export interface CreateBatchJobsResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateBatchJobsResponse
     */
    count: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateBatchJobsResponse
     */
    job_ids: Array<string>;
}

/**
 * Check if a given object implements the CreateBatchJobsResponse interface.
 */
export function instanceOfCreateBatchJobsResponse(value: object): value is CreateBatchJobsResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('job_ids' in value) || value['job_ids'] === undefined) return false;
    return true;
}

export function CreateBatchJobsResponseFromJSON(json: any): CreateBatchJobsResponse {
    return CreateBatchJobsResponseFromJSONTyped(json, false);
}

export function CreateBatchJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBatchJobsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'job_ids': json['job_ids'],
    };
}

export function CreateBatchJobsResponseToJSON(json: any): CreateBatchJobsResponse {
    return CreateBatchJobsResponseToJSONTyped(json, false);
}

export function CreateBatchJobsResponseToJSONTyped(value?: CreateBatchJobsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'job_ids': value['job_ids'],
    };
}

