/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStep } from './WorkflowStep';
import {
    WorkflowStepFromJSON,
    WorkflowStepFromJSONTyped,
    WorkflowStepToJSON,
    WorkflowStepToJSONTyped,
} from './WorkflowStep';

/**
 * Request body for creating a workflow. Shared by the builder DSL and the API
 * so callers and SDKs use the same contract.
 * @export
 * @interface CreateWorkflowRequest
 */
export interface CreateWorkflowRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateWorkflowRequest
     */
    context?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateWorkflowRequest
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CreateWorkflowRequest
     */
    name: string;
    /**
     * 
     * @type {Array<WorkflowStep>}
     * @memberof CreateWorkflowRequest
     */
    steps: Array<WorkflowStep>;
}

/**
 * Check if a given object implements the CreateWorkflowRequest interface.
 */
export function instanceOfCreateWorkflowRequest(value: object): value is CreateWorkflowRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function CreateWorkflowRequestFromJSON(json: any): CreateWorkflowRequest {
    return CreateWorkflowRequestFromJSONTyped(json, false);
}

export function CreateWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['context'] == null ? undefined : json['context'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'steps': ((json['steps'] as Array<any>).map(WorkflowStepFromJSON)),
    };
}

export function CreateWorkflowRequestToJSON(json: any): CreateWorkflowRequest {
    return CreateWorkflowRequestToJSONTyped(json, false);
}

export function CreateWorkflowRequestToJSONTyped(value?: CreateWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': value['context'],
        'metadata': value['metadata'],
        'name': value['name'],
        'steps': ((value['steps'] as Array<any>).map(WorkflowStepToJSON)),
    };
}

