/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobConfigRequest } from './JobConfigRequest';
import {
    JobConfigRequestFromJSON,
    JobConfigRequestFromJSONTyped,
    JobConfigRequestToJSON,
    JobConfigRequestToJSONTyped,
} from './JobConfigRequest';

/**
 * 
 * @export
 * @interface CreateJobRequest
 */
export interface CreateJobRequest {
    /**
     * 
     * @type {JobConfigRequest}
     * @memberof CreateJobRequest
     */
    config?: JobConfigRequest | null;
    /**
     * Arbitrary JSON object passed to the handler.
     * @type {{ [key: string]: any; }}
     * @memberof CreateJobRequest
     */
    payload?: { [key: string]: any; };
    /**
     * Don't run before this instant (RFC 3339). The job is created
     * immediately but stays invisible to workers until then.
     * @type {Date}
     * @memberof CreateJobRequest
     */
    run_at?: Date | null;
    /**
     * The registered task handler to invoke.
     * @type {string}
     * @memberof CreateJobRequest
     */
    task_name: string;
}

/**
 * Check if a given object implements the CreateJobRequest interface.
 */
export function instanceOfCreateJobRequest(value: object): value is CreateJobRequest {
    if (!('task_name' in value) || value['task_name'] === undefined) return false;
    return true;
}

export function CreateJobRequestFromJSON(json: any): CreateJobRequest {
    return CreateJobRequestFromJSONTyped(json, false);
}

export function CreateJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : JobConfigRequestFromJSON(json['config']),
        'payload': json['payload'] == null ? undefined : json['payload'],
        'run_at': json['run_at'] == null ? undefined : (new Date(json['run_at'])),
        'task_name': json['task_name'],
    };
}

export function CreateJobRequestToJSON(json: any): CreateJobRequest {
    return CreateJobRequestToJSONTyped(json, false);
}

export function CreateJobRequestToJSONTyped(value?: CreateJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': JobConfigRequestToJSON(value['config']),
        'payload': value['payload'],
        'run_at': value['run_at'] == null ? undefined : ((value['run_at'] as any).toISOString()),
        'task_name': value['task_name'],
    };
}

