/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkflowResponse
 */
export interface CreateWorkflowResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkflowResponse
     */
    workflow_id: string;
}

/**
 * Check if a given object implements the CreateWorkflowResponse interface.
 */
export function instanceOfCreateWorkflowResponse(value: object): value is CreateWorkflowResponse {
    if (!('workflow_id' in value) || value['workflow_id'] === undefined) return false;
    return true;
}

export function CreateWorkflowResponseFromJSON(json: any): CreateWorkflowResponse {
    return CreateWorkflowResponseFromJSONTyped(json, false);
}

export function CreateWorkflowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkflowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workflow_id': json['workflow_id'],
    };
}

export function CreateWorkflowResponseToJSON(json: any): CreateWorkflowResponse {
    return CreateWorkflowResponseToJSONTyped(json, false);
}

export function CreateWorkflowResponseToJSONTyped(value?: CreateWorkflowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow_id': value['workflow_id'],
    };
}

