/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobConfig } from './JobConfig';
import {
    JobConfigFromJSON,
    JobConfigFromJSONTyped,
    JobConfigToJSON,
    JobConfigToJSONTyped,
} from './JobConfig';

/**
 * Request body for creating a cron schedule.
 * @export
 * @interface CreateCronRequest
 */
export interface CreateCronRequest {
    /**
     * 
     * @type {JobConfig}
     * @memberof CreateCronRequest
     */
    config?: JobConfig | null;
    /**
     * 5-field crontab (UTC); 6/7 fields with leading seconds also accepted.
     * @type {string}
     * @memberof CreateCronRequest
     */
    cron_expr: string;
    /**
     * Unique per tenant.
     * @type {string}
     * @memberof CreateCronRequest
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateCronRequest
     */
    payload?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CreateCronRequest
     */
    queue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCronRequest
     */
    task_name: string;
}

/**
 * Check if a given object implements the CreateCronRequest interface.
 */
export function instanceOfCreateCronRequest(value: object): value is CreateCronRequest {
    if (!('cron_expr' in value) || value['cron_expr'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('task_name' in value) || value['task_name'] === undefined) return false;
    return true;
}

export function CreateCronRequestFromJSON(json: any): CreateCronRequest {
    return CreateCronRequestFromJSONTyped(json, false);
}

export function CreateCronRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCronRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : JobConfigFromJSON(json['config']),
        'cron_expr': json['cron_expr'],
        'name': json['name'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'queue': json['queue'] == null ? undefined : json['queue'],
        'task_name': json['task_name'],
    };
}

export function CreateCronRequestToJSON(json: any): CreateCronRequest {
    return CreateCronRequestToJSONTyped(json, false);
}

export function CreateCronRequestToJSONTyped(value?: CreateCronRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': JobConfigToJSON(value['config']),
        'cron_expr': value['cron_expr'],
        'name': value['name'],
        'payload': value['payload'],
        'queue': value['queue'],
        'task_name': value['task_name'],
    };
}

