/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobConfig } from './JobConfig';
import {
    JobConfigFromJSON,
    JobConfigFromJSONTyped,
    JobConfigToJSON,
    JobConfigToJSONTyped,
} from './JobConfig';

/**
 * A recurring enqueue schedule. Expressions are standard 5-field crontab
 * (`minute hour day-of-month month day-of-week`), evaluated in **UTC**; a
 * 6/7-field form with leading seconds is also accepted.
 * @export
 * @interface CronSchedule
 */
export interface CronSchedule {
    /**
     * 
     * @type {JobConfig}
     * @memberof CronSchedule
     */
    config?: JobConfig | null;
    /**
     * 
     * @type {Date}
     * @memberof CronSchedule
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof CronSchedule
     */
    cron_expr: string;
    /**
     * 
     * @type {boolean}
     * @memberof CronSchedule
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof CronSchedule
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CronSchedule
     */
    last_enqueued_at?: Date | null;
    /**
     * Unique per tenant.
     * @type {string}
     * @memberof CronSchedule
     */
    name: string;
    /**
     * The next instant this schedule fires. Missed occurrences (server
     * down) collapse into at most one catch-up firing.
     * @type {Date}
     * @memberof CronSchedule
     */
    next_run_at: Date;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CronSchedule
     */
    payload?: { [key: string]: any; };
    /**
     * Queue for the enqueued jobs (the engine default when absent).
     * @type {string}
     * @memberof CronSchedule
     */
    queue_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CronSchedule
     */
    task_name: string;
    /**
     * 
     * @type {string}
     * @memberof CronSchedule
     */
    tenant_id?: string | null;
}

/**
 * Check if a given object implements the CronSchedule interface.
 */
export function instanceOfCronSchedule(value: object): value is CronSchedule {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('cron_expr' in value) || value['cron_expr'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('next_run_at' in value) || value['next_run_at'] === undefined) return false;
    if (!('task_name' in value) || value['task_name'] === undefined) return false;
    return true;
}

export function CronScheduleFromJSON(json: any): CronSchedule {
    return CronScheduleFromJSONTyped(json, false);
}

export function CronScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CronSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : JobConfigFromJSON(json['config']),
        'created_at': (new Date(json['created_at'])),
        'cron_expr': json['cron_expr'],
        'enabled': json['enabled'],
        'id': json['id'],
        'last_enqueued_at': json['last_enqueued_at'] == null ? undefined : (new Date(json['last_enqueued_at'])),
        'name': json['name'],
        'next_run_at': (new Date(json['next_run_at'])),
        'payload': json['payload'] == null ? undefined : json['payload'],
        'queue_name': json['queue_name'] == null ? undefined : json['queue_name'],
        'task_name': json['task_name'],
        'tenant_id': json['tenant_id'] == null ? undefined : json['tenant_id'],
    };
}

export function CronScheduleToJSON(json: any): CronSchedule {
    return CronScheduleToJSONTyped(json, false);
}

export function CronScheduleToJSONTyped(value?: CronSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': JobConfigToJSON(value['config']),
        'created_at': ((value['created_at']).toISOString()),
        'cron_expr': value['cron_expr'],
        'enabled': value['enabled'],
        'id': value['id'],
        'last_enqueued_at': value['last_enqueued_at'] == null ? undefined : ((value['last_enqueued_at'] as any).toISOString()),
        'name': value['name'],
        'next_run_at': ((value['next_run_at']).toISOString()),
        'payload': value['payload'],
        'queue_name': value['queue_name'],
        'task_name': value['task_name'],
        'tenant_id': value['tenant_id'],
    };
}

