/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A dead-lettered job: a terminal failure recorded for inspection and
 * replay. The original job row remains (subject to retention); this entry
 * captures why it died and, once replayed, which fresh job took its place.
 * @export
 * @interface DeadLetter
 */
export interface DeadLetter {
    /**
     * 
     * @type {Date}
     * @memberof DeadLetter
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof DeadLetter
     */
    error_message?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeadLetter
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DeadLetter
     */
    job_id: string;
    /**
     * 
     * @type {string}
     * @memberof DeadLetter
     */
    queue_name?: string | null;
    /**
     * Why the job dead-lettered: `max_attempts_exceeded`, `non_retryable`,
     * or `handler_not_found`.
     * @type {string}
     * @memberof DeadLetter
     */
    reason: string;
    /**
     * The fresh job created by the replay.
     * @type {string}
     * @memberof DeadLetter
     */
    replay_job_id?: string | null;
    /**
     * Set once this entry has been replayed; a dead letter replays at most
     * once.
     * @type {Date}
     * @memberof DeadLetter
     */
    replayed_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DeadLetter
     */
    task_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeadLetter
     */
    tenant_id?: string | null;
}

/**
 * Check if a given object implements the DeadLetter interface.
 */
export function instanceOfDeadLetter(value: object): value is DeadLetter {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('job_id' in value) || value['job_id'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function DeadLetterFromJSON(json: any): DeadLetter {
    return DeadLetterFromJSONTyped(json, false);
}

export function DeadLetterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadLetter {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (new Date(json['created_at'])),
        'error_message': json['error_message'] == null ? undefined : json['error_message'],
        'id': json['id'],
        'job_id': json['job_id'],
        'queue_name': json['queue_name'] == null ? undefined : json['queue_name'],
        'reason': json['reason'],
        'replay_job_id': json['replay_job_id'] == null ? undefined : json['replay_job_id'],
        'replayed_at': json['replayed_at'] == null ? undefined : (new Date(json['replayed_at'])),
        'task_name': json['task_name'] == null ? undefined : json['task_name'],
        'tenant_id': json['tenant_id'] == null ? undefined : json['tenant_id'],
    };
}

export function DeadLetterToJSON(json: any): DeadLetter {
    return DeadLetterToJSONTyped(json, false);
}

export function DeadLetterToJSONTyped(value?: DeadLetter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': ((value['created_at']).toISOString()),
        'error_message': value['error_message'],
        'id': value['id'],
        'job_id': value['job_id'],
        'queue_name': value['queue_name'],
        'reason': value['reason'],
        'replay_job_id': value['replay_job_id'],
        'replayed_at': value['replayed_at'] == null ? undefined : ((value['replayed_at'] as any).toISOString()),
        'task_name': value['task_name'],
        'tenant_id': value['tenant_id'],
    };
}

