/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorBody
 */
export interface ErrorBody {
    /**
     * 
     * @type {string}
     * @memberof ErrorBody
     */
    error: string;
    /**
     * 
     * @type {Date}
     * @memberof ErrorBody
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ErrorBody interface.
 */
export function instanceOfErrorBody(value: object): value is ErrorBody {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ErrorBodyFromJSON(json: any): ErrorBody {
    return ErrorBodyFromJSONTyped(json, false);
}

export function ErrorBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorBody {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ErrorBodyToJSON(json: any): ErrorBody {
    return ErrorBodyToJSONTyped(json, false);
}

export function ErrorBodyToJSONTyped(value?: ErrorBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

