/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for `POST /api/v1/jobs/{id}/fail`.
 * @export
 * @interface FailJobRequest
 */
export interface FailJobRequest {
    /**
     * Human-readable failure reason.
     * @type {string}
     * @memberof FailJobRequest
     */
    error: string;
    /**
     * The lease token returned by the lease call.
     * @type {string}
     * @memberof FailJobRequest
     */
    lease_token: string;
    /**
     * Whether the engine may retry (subject to the job's max_retries).
     * Defaults to true; send false for permanent failures (e.g. bad input).
     * @type {boolean}
     * @memberof FailJobRequest
     */
    retryable?: boolean;
}

/**
 * Check if a given object implements the FailJobRequest interface.
 */
export function instanceOfFailJobRequest(value: object): value is FailJobRequest {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('lease_token' in value) || value['lease_token'] === undefined) return false;
    return true;
}

export function FailJobRequestFromJSON(json: any): FailJobRequest {
    return FailJobRequestFromJSONTyped(json, false);
}

export function FailJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FailJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'lease_token': json['lease_token'],
        'retryable': json['retryable'] == null ? undefined : json['retryable'],
    };
}

export function FailJobRequestToJSON(json: any): FailJobRequest {
    return FailJobRequestToJSONTyped(json, false);
}

export function FailJobRequestToJSONTyped(value?: FailJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'lease_token': value['lease_token'],
        'retryable': value['retryable'],
    };
}

