/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthStatus
 */
export interface HealthStatus {
    /**
     * 
     * @type {string}
     * @memberof HealthStatus
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof HealthStatus
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof HealthStatus
     */
    version: string;
}

/**
 * Check if a given object implements the HealthStatus interface.
 */
export function instanceOfHealthStatus(value: object): value is HealthStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function HealthStatusFromJSON(json: any): HealthStatus {
    return HealthStatusFromJSONTyped(json, false);
}

export function HealthStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': (new Date(json['timestamp'])),
        'version': json['version'],
    };
}

export function HealthStatusToJSON(json: any): HealthStatus {
    return HealthStatusToJSONTyped(json, false);
}

export function HealthStatusToJSONTyped(value?: HealthStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': ((value['timestamp']).toISOString()),
        'version': value['version'],
    };
}

