/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';

/**
 * Response for `POST /api/v1/jobs/{id}/heartbeat`.
 * @export
 * @interface HeartbeatResponse
 */
export interface HeartbeatResponse {
    /**
     * The job's current status. `running` means the lease was extended;
     * anything else (`cancelled`, `completed`, ...) means it was not, and
     * the worker should stop working on the job.
     * @type {JobStatus}
     * @memberof HeartbeatResponse
     */
    status: JobStatus;
}



/**
 * Check if a given object implements the HeartbeatResponse interface.
 */
export function instanceOfHeartbeatResponse(value: object): value is HeartbeatResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HeartbeatResponseFromJSON(json: any): HeartbeatResponse {
    return HeartbeatResponseFromJSONTyped(json, false);
}

export function HeartbeatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeartbeatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': JobStatusFromJSON(json['status']),
    };
}

export function HeartbeatResponseToJSON(json: any): HeartbeatResponse {
    return HeartbeatResponseToJSONTyped(json, false);
}

export function HeartbeatResponseToJSONTyped(value?: HeartbeatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': JobStatusToJSON(value['status']),
    };
}

