/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for `POST /api/v1/jobs/{id}/heartbeat`.
 * @export
 * @interface HeartbeatRequest
 */
export interface HeartbeatRequest {
    /**
     * New lease duration in seconds, measured from now (1..=3600).
     * @type {number}
     * @memberof HeartbeatRequest
     */
    extend_secs: number;
    /**
     * The lease token returned by the lease call.
     * @type {string}
     * @memberof HeartbeatRequest
     */
    lease_token: string;
}

/**
 * Check if a given object implements the HeartbeatRequest interface.
 */
export function instanceOfHeartbeatRequest(value: object): value is HeartbeatRequest {
    if (!('extend_secs' in value) || value['extend_secs'] === undefined) return false;
    if (!('lease_token' in value) || value['lease_token'] === undefined) return false;
    return true;
}

export function HeartbeatRequestFromJSON(json: any): HeartbeatRequest {
    return HeartbeatRequestFromJSONTyped(json, false);
}

export function HeartbeatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeartbeatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'extend_secs': json['extend_secs'],
        'lease_token': json['lease_token'],
    };
}

export function HeartbeatRequestToJSON(json: any): HeartbeatRequest {
    return HeartbeatRequestToJSONTyped(json, false);
}

export function HeartbeatRequestToJSONTyped(value?: HeartbeatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extend_secs': value['extend_secs'],
        'lease_token': value['lease_token'],
    };
}

