/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';
import type { JobConfig } from './JobConfig';
import {
    JobConfigFromJSON,
    JobConfigFromJSONTyped,
    JobConfigToJSON,
    JobConfigToJSONTyped,
} from './JobConfig';

/**
 * A single unit of work.
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    completed_at?: Date | null;
    /**
     * 
     * @type {JobConfig}
     * @memberof Job
     */
    config: JobConfig;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    created_at: Date;
    /**
     * How many times this job has been claimed (delivered to a worker).
     * Greater than `retry_count + 1` means a lease expired without a report —
     * i.e. a worker crashed mid-run.
     * @type {number}
     * @memberof Job
     */
    delivery_count?: number;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    error_message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    id: string;
    /**
     * Client-supplied key that makes job creation idempotent per tenant:
     * re-submitting the same key returns the original job instead of creating
     * a duplicate.
     * @type {string}
     * @memberof Job
     */
    idempotency_key?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Job
     */
    metadata?: { [key: string]: any; };
    /**
     * When this job's next retry becomes claimable (mirrors `scheduled_at`
     * while the job is `retrying`; kept for audit/inspection).
     * @type {Date}
     * @memberof Job
     */
    next_retry_at?: Date | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Job
     */
    payload?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    queue_name: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Job
     */
    result?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    retry_count: number;
    /**
     * When the job becomes claimable. `created_at` for immediate jobs, the
     * requested `run_at` for scheduled jobs, and the next backoff instant
     * while retrying — the durable delay lives in the row itself.
     * @type {Date}
     * @memberof Job
     */
    scheduled_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    started_at?: Date | null;
    /**
     * 
     * @type {JobStatus}
     * @memberof Job
     */
    status: JobStatus;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    task_name: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    tenant_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    workflow_id?: string | null;
    /**
     * The owning workflow step's name (steps are addressed by name).
     * @type {string}
     * @memberof Job
     */
    workflow_step_id?: string | null;
}



/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('queue_name' in value) || value['queue_name'] === undefined) return false;
    if (!('retry_count' in value) || value['retry_count'] === undefined) return false;
    if (!('scheduled_at' in value) || value['scheduled_at'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('task_name' in value) || value['task_name'] === undefined) return false;
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'completed_at': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'config': JobConfigFromJSON(json['config']),
        'created_at': (new Date(json['created_at'])),
        'delivery_count': json['delivery_count'] == null ? undefined : json['delivery_count'],
        'error_message': json['error_message'] == null ? undefined : json['error_message'],
        'id': json['id'],
        'idempotency_key': json['idempotency_key'] == null ? undefined : json['idempotency_key'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'next_retry_at': json['next_retry_at'] == null ? undefined : (new Date(json['next_retry_at'])),
        'payload': json['payload'] == null ? undefined : json['payload'],
        'queue_name': json['queue_name'],
        'result': json['result'] == null ? undefined : json['result'],
        'retry_count': json['retry_count'],
        'scheduled_at': (new Date(json['scheduled_at'])),
        'started_at': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'status': JobStatusFromJSON(json['status']),
        'task_name': json['task_name'],
        'tenant_id': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'workflow_id': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'workflow_step_id': json['workflow_step_id'] == null ? undefined : json['workflow_step_id'],
    };
}

export function JobToJSON(json: any): Job {
    return JobToJSONTyped(json, false);
}

export function JobToJSONTyped(value?: Job | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed_at': value['completed_at'] == null ? undefined : ((value['completed_at'] as any).toISOString()),
        'config': JobConfigToJSON(value['config']),
        'created_at': ((value['created_at']).toISOString()),
        'delivery_count': value['delivery_count'],
        'error_message': value['error_message'],
        'id': value['id'],
        'idempotency_key': value['idempotency_key'],
        'metadata': value['metadata'],
        'next_retry_at': value['next_retry_at'] == null ? undefined : ((value['next_retry_at'] as any).toISOString()),
        'payload': value['payload'],
        'queue_name': value['queue_name'],
        'result': value['result'],
        'retry_count': value['retry_count'],
        'scheduled_at': ((value['scheduled_at']).toISOString()),
        'started_at': value['started_at'] == null ? undefined : ((value['started_at'] as any).toISOString()),
        'status': JobStatusToJSON(value['status']),
        'task_name': value['task_name'],
        'tenant_id': value['tenant_id'],
        'workflow_id': value['workflow_id'],
        'workflow_step_id': value['workflow_step_id'],
    };
}

