/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional per-job configuration overrides.
 * @export
 * @interface JobConfigRequest
 */
export interface JobConfigRequest {
    /**
     * 
     * @type {number}
     * @memberof JobConfigRequest
     */
    max_retries?: number | null;
    /**
     * Higher is claimed first within a queue (ties: oldest first).
     * @type {number}
     * @memberof JobConfigRequest
     */
    priority?: number | null;
    /**
     * Override the destination queue.
     * @type {string}
     * @memberof JobConfigRequest
     */
    queue?: string | null;
    /**
     * Per-attempt timeout, in seconds.
     * @type {number}
     * @memberof JobConfigRequest
     */
    timeout?: number | null;
}

/**
 * Check if a given object implements the JobConfigRequest interface.
 */
export function instanceOfJobConfigRequest(value: object): value is JobConfigRequest {
    return true;
}

export function JobConfigRequestFromJSON(json: any): JobConfigRequest {
    return JobConfigRequestFromJSONTyped(json, false);
}

export function JobConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'max_retries': json['max_retries'] == null ? undefined : json['max_retries'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'queue': json['queue'] == null ? undefined : json['queue'],
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
    };
}

export function JobConfigRequestToJSON(json: any): JobConfigRequest {
    return JobConfigRequestToJSONTyped(json, false);
}

export function JobConfigRequestToJSONTyped(value?: JobConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_retries': value['max_retries'],
        'priority': value['priority'],
        'queue': value['queue'],
        'timeout': value['timeout'],
    };
}

