/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackoffStrategy } from './BackoffStrategy';
import {
    BackoffStrategyFromJSON,
    BackoffStrategyFromJSONTyped,
    BackoffStrategyToJSON,
    BackoffStrategyToJSONTyped,
} from './BackoffStrategy';

/**
 * Per-job execution configuration. All durations are in seconds.
 * @export
 * @interface JobConfig
 */
export interface JobConfig {
    /**
     * Optional jitter in `0.0..=1.0`. `0.1` => +/-10% randomization of each
     * retry delay, which spreads out thundering-herd retries.
     * @type {number}
     * @memberof JobConfig
     */
    jitter_factor?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobConfig
     */
    max_retries: number;
    /**
     * Higher is claimed first within a queue; ties break on `scheduled_at`,
     * then `created_at`.
     * @type {number}
     * @memberof JobConfig
     */
    priority: number;
    /**
     * 
     * @type {BackoffStrategy}
     * @memberof JobConfig
     */
    retry_backoff?: BackoffStrategy;
    /**
     * 
     * @type {number}
     * @memberof JobConfig
     */
    retry_delay_secs: number;
    /**
     * 
     * @type {number}
     * @memberof JobConfig
     */
    retry_max_delay_secs: number;
    /**
     * 
     * @type {number}
     * @memberof JobConfig
     */
    timeout_secs: number;
}



/**
 * Check if a given object implements the JobConfig interface.
 */
export function instanceOfJobConfig(value: object): value is JobConfig {
    if (!('max_retries' in value) || value['max_retries'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('retry_delay_secs' in value) || value['retry_delay_secs'] === undefined) return false;
    if (!('retry_max_delay_secs' in value) || value['retry_max_delay_secs'] === undefined) return false;
    if (!('timeout_secs' in value) || value['timeout_secs'] === undefined) return false;
    return true;
}

export function JobConfigFromJSON(json: any): JobConfig {
    return JobConfigFromJSONTyped(json, false);
}

export function JobConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'jitter_factor': json['jitter_factor'] == null ? undefined : json['jitter_factor'],
        'max_retries': json['max_retries'],
        'priority': json['priority'],
        'retry_backoff': json['retry_backoff'] == null ? undefined : BackoffStrategyFromJSON(json['retry_backoff']),
        'retry_delay_secs': json['retry_delay_secs'],
        'retry_max_delay_secs': json['retry_max_delay_secs'],
        'timeout_secs': json['timeout_secs'],
    };
}

export function JobConfigToJSON(json: any): JobConfig {
    return JobConfigToJSONTyped(json, false);
}

export function JobConfigToJSONTyped(value?: JobConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jitter_factor': value['jitter_factor'],
        'max_retries': value['max_retries'],
        'priority': value['priority'],
        'retry_backoff': BackoffStrategyToJSON(value['retry_backoff']),
        'retry_delay_secs': value['retry_delay_secs'],
        'retry_max_delay_secs': value['retry_max_delay_secs'],
        'timeout_secs': value['timeout_secs'],
    };
}

