/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Job } from './Job';
import {
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    JobToJSONTyped,
} from './Job';

/**
 * A job leased to a (possibly remote) worker, together with the lease token
 * needed to heartbeat, complete, or fail it.
 * @export
 * @interface LeasedJob
 */
export interface LeasedJob {
    /**
     * 
     * @type {Job}
     * @memberof LeasedJob
     */
    job: Job;
    /**
     * Opaque, unguessable proof of lease ownership, regenerated on every
     * claim. Pass it back on heartbeat/complete/fail; a stale token (the
     * lease expired and the job was reclaimed) is rejected.
     * @type {string}
     * @memberof LeasedJob
     */
    lease_token: string;
}

/**
 * Check if a given object implements the LeasedJob interface.
 */
export function instanceOfLeasedJob(value: object): value is LeasedJob {
    if (!('job' in value) || value['job'] === undefined) return false;
    if (!('lease_token' in value) || value['lease_token'] === undefined) return false;
    return true;
}

export function LeasedJobFromJSON(json: any): LeasedJob {
    return LeasedJobFromJSONTyped(json, false);
}

export function LeasedJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeasedJob {
    if (json == null) {
        return json;
    }
    return {
        
        'job': JobFromJSON(json['job']),
        'lease_token': json['lease_token'],
    };
}

export function LeasedJobToJSON(json: any): LeasedJob {
    return LeasedJobToJSONTyped(json, false);
}

export function LeasedJobToJSONTyped(value?: LeasedJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job': JobToJSON(value['job']),
        'lease_token': value['lease_token'],
    };
}

