/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeasedJob } from './LeasedJob';
import {
    LeasedJobFromJSON,
    LeasedJobFromJSONTyped,
    LeasedJobToJSON,
    LeasedJobToJSONTyped,
} from './LeasedJob';

/**
 * 
 * @export
 * @interface LeaseJobsResponse
 */
export interface LeaseJobsResponse {
    /**
     * 
     * @type {Array<LeasedJob>}
     * @memberof LeaseJobsResponse
     */
    jobs: Array<LeasedJob>;
}

/**
 * Check if a given object implements the LeaseJobsResponse interface.
 */
export function instanceOfLeaseJobsResponse(value: object): value is LeaseJobsResponse {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    return true;
}

export function LeaseJobsResponseFromJSON(json: any): LeaseJobsResponse {
    return LeaseJobsResponseFromJSONTyped(json, false);
}

export function LeaseJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaseJobsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(LeasedJobFromJSON)),
    };
}

export function LeaseJobsResponseToJSON(json: any): LeaseJobsResponse {
    return LeaseJobsResponseToJSONTyped(json, false);
}

export function LeaseJobsResponseToJSONTyped(value?: LeaseJobsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': ((value['jobs'] as Array<any>).map(LeasedJobToJSON)),
    };
}

