/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for `POST /api/v1/queues/{queue}/lease`.
 * @export
 * @interface LeaseJobsRequest
 */
export interface LeaseJobsRequest {
    /**
     * Lease duration in seconds (1..=3600, default 30). Heartbeat to extend.
     * @type {number}
     * @memberof LeaseJobsRequest
     */
    lease_secs?: number | null;
    /**
     * Maximum jobs to lease in one call (1..=100, default 1).
     * @type {number}
     * @memberof LeaseJobsRequest
     */
    max_jobs?: number | null;
    /**
     * Long-poll wait when the queue is empty, in seconds (0..=30, default 0).
     * @type {number}
     * @memberof LeaseJobsRequest
     */
    wait_secs?: number | null;
}

/**
 * Check if a given object implements the LeaseJobsRequest interface.
 */
export function instanceOfLeaseJobsRequest(value: object): value is LeaseJobsRequest {
    return true;
}

export function LeaseJobsRequestFromJSON(json: any): LeaseJobsRequest {
    return LeaseJobsRequestFromJSONTyped(json, false);
}

export function LeaseJobsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaseJobsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lease_secs': json['lease_secs'] == null ? undefined : json['lease_secs'],
        'max_jobs': json['max_jobs'] == null ? undefined : json['max_jobs'],
        'wait_secs': json['wait_secs'] == null ? undefined : json['wait_secs'],
    };
}

export function LeaseJobsRequestToJSON(json: any): LeaseJobsRequest {
    return LeaseJobsRequestToJSONTyped(json, false);
}

export function LeaseJobsRequestToJSONTyped(value?: LeaseJobsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lease_secs': value['lease_secs'],
        'max_jobs': value['max_jobs'],
        'wait_secs': value['wait_secs'],
    };
}

