/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CronSchedule } from './CronSchedule';
import {
    CronScheduleFromJSON,
    CronScheduleFromJSONTyped,
    CronScheduleToJSON,
    CronScheduleToJSONTyped,
} from './CronSchedule';

/**
 * 
 * @export
 * @interface ListCronsResponse
 */
export interface ListCronsResponse {
    /**
     * 
     * @type {Array<CronSchedule>}
     * @memberof ListCronsResponse
     */
    crons: Array<CronSchedule>;
    /**
     * 
     * @type {boolean}
     * @memberof ListCronsResponse
     */
    has_more: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListCronsResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListCronsResponse
     */
    offset: number;
    /**
     * Exact total match count; only present when `include_total=true`.
     * @type {number}
     * @memberof ListCronsResponse
     */
    total?: number | null;
}

/**
 * Check if a given object implements the ListCronsResponse interface.
 */
export function instanceOfListCronsResponse(value: object): value is ListCronsResponse {
    if (!('crons' in value) || value['crons'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListCronsResponseFromJSON(json: any): ListCronsResponse {
    return ListCronsResponseFromJSONTyped(json, false);
}

export function ListCronsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCronsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'crons': ((json['crons'] as Array<any>).map(CronScheduleFromJSON)),
        'has_more': json['has_more'],
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListCronsResponseToJSON(json: any): ListCronsResponse {
    return ListCronsResponseToJSONTyped(json, false);
}

export function ListCronsResponseToJSONTyped(value?: ListCronsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'crons': ((value['crons'] as Array<any>).map(CronScheduleToJSON)),
        'has_more': value['has_more'],
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

