/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeadLetter } from './DeadLetter';
import {
    DeadLetterFromJSON,
    DeadLetterFromJSONTyped,
    DeadLetterToJSON,
    DeadLetterToJSONTyped,
} from './DeadLetter';

/**
 * 
 * @export
 * @interface ListDeadLettersResponse
 */
export interface ListDeadLettersResponse {
    /**
     * 
     * @type {Array<DeadLetter>}
     * @memberof ListDeadLettersResponse
     */
    dead_letters: Array<DeadLetter>;
    /**
     * 
     * @type {boolean}
     * @memberof ListDeadLettersResponse
     */
    has_more: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListDeadLettersResponse
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListDeadLettersResponse
     */
    offset: number;
    /**
     * Exact total match count; only present when `include_total=true`.
     * @type {number}
     * @memberof ListDeadLettersResponse
     */
    total?: number | null;
}

/**
 * Check if a given object implements the ListDeadLettersResponse interface.
 */
export function instanceOfListDeadLettersResponse(value: object): value is ListDeadLettersResponse {
    if (!('dead_letters' in value) || value['dead_letters'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListDeadLettersResponseFromJSON(json: any): ListDeadLettersResponse {
    return ListDeadLettersResponseFromJSONTyped(json, false);
}

export function ListDeadLettersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDeadLettersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dead_letters': ((json['dead_letters'] as Array<any>).map(DeadLetterFromJSON)),
        'has_more': json['has_more'],
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListDeadLettersResponseToJSON(json: any): ListDeadLettersResponse {
    return ListDeadLettersResponseToJSONTyped(json, false);
}

export function ListDeadLettersResponseToJSONTyped(value?: ListDeadLettersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dead_letters': ((value['dead_letters'] as Array<any>).map(DeadLetterToJSON)),
        'has_more': value['has_more'],
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

