/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Workflow } from './Workflow';
import {
    WorkflowFromJSON,
    WorkflowFromJSONTyped,
    WorkflowToJSON,
    WorkflowToJSONTyped,
} from './Workflow';

/**
 * 
 * @export
 * @interface ListWorkflowsResponse
 */
export interface ListWorkflowsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListWorkflowsResponse
     */
    has_more: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListWorkflowsResponse
     */
    limit: number;
    /**
     * Opaque keyset cursor for the next page (present when `has_more`).
     * Pass it back as `cursor` to continue where this page ended; cheaper
     * than deep OFFSET paging.
     * @type {string}
     * @memberof ListWorkflowsResponse
     */
    next_cursor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListWorkflowsResponse
     */
    offset: number;
    /**
     * Exact total match count; only present when `include_total=true`.
     * @type {number}
     * @memberof ListWorkflowsResponse
     */
    total?: number | null;
    /**
     * 
     * @type {Array<Workflow>}
     * @memberof ListWorkflowsResponse
     */
    workflows: Array<Workflow>;
}

/**
 * Check if a given object implements the ListWorkflowsResponse interface.
 */
export function instanceOfListWorkflowsResponse(value: object): value is ListWorkflowsResponse {
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('workflows' in value) || value['workflows'] === undefined) return false;
    return true;
}

export function ListWorkflowsResponseFromJSON(json: any): ListWorkflowsResponse {
    return ListWorkflowsResponseFromJSONTyped(json, false);
}

export function ListWorkflowsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkflowsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'has_more': json['has_more'],
        'limit': json['limit'],
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'offset': json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
        'workflows': ((json['workflows'] as Array<any>).map(WorkflowFromJSON)),
    };
}

export function ListWorkflowsResponseToJSON(json: any): ListWorkflowsResponse {
    return ListWorkflowsResponseToJSONTyped(json, false);
}

export function ListWorkflowsResponseToJSONTyped(value?: ListWorkflowsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_more': value['has_more'],
        'limit': value['limit'],
        'next_cursor': value['next_cursor'],
        'offset': value['offset'],
        'total': value['total'],
        'workflows': ((value['workflows'] as Array<any>).map(WorkflowToJSON)),
    };
}

