/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Job } from './Job';
import {
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    JobToJSONTyped,
} from './Job';

/**
 * 
 * @export
 * @interface ListJobsResponse
 */
export interface ListJobsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListJobsResponse
     */
    has_more: boolean;
    /**
     * 
     * @type {Array<Job>}
     * @memberof ListJobsResponse
     */
    jobs: Array<Job>;
    /**
     * 
     * @type {number}
     * @memberof ListJobsResponse
     */
    limit: number;
    /**
     * Opaque keyset cursor for the next page (present when `has_more`).
     * Pass it back as `cursor` to continue where this page ended; cheaper
     * than deep OFFSET paging.
     * @type {string}
     * @memberof ListJobsResponse
     */
    next_cursor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListJobsResponse
     */
    offset: number;
    /**
     * Exact total match count. Only present when the request set
     * `include_total=true`; computing it costs a full count over the filtered
     * set, so it is opt-in.
     * @type {number}
     * @memberof ListJobsResponse
     */
    total?: number | null;
}

/**
 * Check if a given object implements the ListJobsResponse interface.
 */
export function instanceOfListJobsResponse(value: object): value is ListJobsResponse {
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListJobsResponseFromJSON(json: any): ListJobsResponse {
    return ListJobsResponseFromJSONTyped(json, false);
}

export function ListJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'has_more': json['has_more'],
        'jobs': ((json['jobs'] as Array<any>).map(JobFromJSON)),
        'limit': json['limit'],
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'offset': json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListJobsResponseToJSON(json: any): ListJobsResponse {
    return ListJobsResponseToJSONTyped(json, false);
}

export function ListJobsResponseToJSONTyped(value?: ListJobsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_more': value['has_more'],
        'jobs': ((value['jobs'] as Array<any>).map(JobToJSON)),
        'limit': value['limit'],
        'next_cursor': value['next_cursor'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

