/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What to do with downstream steps when a step fails.
 * @export
 */
export const OnFailure = {
    Halt: 'halt',
    Skip: 'skip',
    Continue: 'continue'
} as const;
export type OnFailure = typeof OnFailure[keyof typeof OnFailure];


export function instanceOfOnFailure(value: any): boolean {
    for (const key in OnFailure) {
        if (Object.prototype.hasOwnProperty.call(OnFailure, key)) {
            if (OnFailure[key as keyof typeof OnFailure] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OnFailureFromJSON(json: any): OnFailure {
    return OnFailureFromJSONTyped(json, false);
}

export function OnFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnFailure {
    return json as OnFailure;
}

export function OnFailureToJSON(value?: OnFailure | null): any {
    return value as any;
}

export function OnFailureToJSONTyped(value: any, ignoreDiscriminator: boolean): OnFailure {
    return value as OnFailure;
}

