/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Reserved for future expansion; only `Continue` is meaningful today.
 * @export
 */
export const OnSuccess = {
    Continue: 'continue'
} as const;
export type OnSuccess = typeof OnSuccess[keyof typeof OnSuccess];


export function instanceOfOnSuccess(value: any): boolean {
    for (const key in OnSuccess) {
        if (Object.prototype.hasOwnProperty.call(OnSuccess, key)) {
            if (OnSuccess[key as keyof typeof OnSuccess] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OnSuccessFromJSON(json: any): OnSuccess {
    return OnSuccessFromJSONTyped(json, false);
}

export function OnSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnSuccess {
    return json as OnSuccess;
}

export function OnSuccessToJSON(value?: OnSuccess | null): any {
    return value as any;
}

export function OnSuccessToJSONTyped(value: any, ignoreDiscriminator: boolean): OnSuccess {
    return value as OnSuccess;
}

