/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadyStatus
 */
export interface ReadyStatus {
    /**
     * 
     * @type {string}
     * @memberof ReadyStatus
     */
    status: string;
}

/**
 * Check if a given object implements the ReadyStatus interface.
 */
export function instanceOfReadyStatus(value: object): value is ReadyStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ReadyStatusFromJSON(json: any): ReadyStatus {
    return ReadyStatusFromJSONTyped(json, false);
}

export function ReadyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadyStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ReadyStatusToJSON(json: any): ReadyStatus {
    return ReadyStatusToJSONTyped(json, false);
}

export function ReadyStatusToJSONTyped(value?: ReadyStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

