/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplayDeadLetterResponse
 */
export interface ReplayDeadLetterResponse {
    /**
     * The fresh job created from the dead-lettered one.
     * @type {string}
     * @memberof ReplayDeadLetterResponse
     */
    job_id: string;
}

/**
 * Check if a given object implements the ReplayDeadLetterResponse interface.
 */
export function instanceOfReplayDeadLetterResponse(value: object): value is ReplayDeadLetterResponse {
    if (!('job_id' in value) || value['job_id'] === undefined) return false;
    return true;
}

export function ReplayDeadLetterResponseFromJSON(json: any): ReplayDeadLetterResponse {
    return ReplayDeadLetterResponseFromJSONTyped(json, false);
}

export function ReplayDeadLetterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayDeadLetterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'job_id': json['job_id'],
    };
}

export function ReplayDeadLetterResponseToJSON(json: any): ReplayDeadLetterResponse {
    return ReplayDeadLetterResponseToJSONTyped(json, false);
}

export function ReplayDeadLetterResponseToJSONTyped(value?: ReplayDeadLetterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['job_id'],
    };
}

