/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Plain snapshot of [`EngineStats`].
 * @export
 * @interface StatsSnapshot
 */
export interface StatsSnapshot {
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    jobs_completed: number;
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    jobs_created: number;
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    jobs_dead_lettered: number;
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    jobs_failed: number;
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    jobs_retried: number;
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    workflows_completed: number;
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    workflows_created: number;
    /**
     * 
     * @type {number}
     * @memberof StatsSnapshot
     */
    workflows_failed: number;
}

/**
 * Check if a given object implements the StatsSnapshot interface.
 */
export function instanceOfStatsSnapshot(value: object): value is StatsSnapshot {
    if (!('jobs_completed' in value) || value['jobs_completed'] === undefined) return false;
    if (!('jobs_created' in value) || value['jobs_created'] === undefined) return false;
    if (!('jobs_dead_lettered' in value) || value['jobs_dead_lettered'] === undefined) return false;
    if (!('jobs_failed' in value) || value['jobs_failed'] === undefined) return false;
    if (!('jobs_retried' in value) || value['jobs_retried'] === undefined) return false;
    if (!('workflows_completed' in value) || value['workflows_completed'] === undefined) return false;
    if (!('workflows_created' in value) || value['workflows_created'] === undefined) return false;
    if (!('workflows_failed' in value) || value['workflows_failed'] === undefined) return false;
    return true;
}

export function StatsSnapshotFromJSON(json: any): StatsSnapshot {
    return StatsSnapshotFromJSONTyped(json, false);
}

export function StatsSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs_completed': json['jobs_completed'],
        'jobs_created': json['jobs_created'],
        'jobs_dead_lettered': json['jobs_dead_lettered'],
        'jobs_failed': json['jobs_failed'],
        'jobs_retried': json['jobs_retried'],
        'workflows_completed': json['workflows_completed'],
        'workflows_created': json['workflows_created'],
        'workflows_failed': json['workflows_failed'],
    };
}

export function StatsSnapshotToJSON(json: any): StatsSnapshot {
    return StatsSnapshotToJSONTyped(json, false);
}

export function StatsSnapshotToJSONTyped(value?: StatsSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs_completed': value['jobs_completed'],
        'jobs_created': value['jobs_created'],
        'jobs_dead_lettered': value['jobs_dead_lettered'],
        'jobs_failed': value['jobs_failed'],
        'jobs_retried': value['jobs_retried'],
        'workflows_completed': value['workflows_completed'],
        'workflows_created': value['workflows_created'],
        'workflows_failed': value['workflows_failed'],
    };
}

