/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TasksResponse
 */
export interface TasksResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof TasksResponse
     */
    tasks: Array<string>;
}

/**
 * Check if a given object implements the TasksResponse interface.
 */
export function instanceOfTasksResponse(value: object): value is TasksResponse {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function TasksResponseFromJSON(json: any): TasksResponse {
    return TasksResponseFromJSONTyped(json, false);
}

export function TasksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': json['tasks'],
    };
}

export function TasksResponseToJSON(json: any): TasksResponse {
    return TasksResponseToJSONTyped(json, false);
}

export function TasksResponseToJSONTyped(value?: TasksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tasks': value['tasks'],
    };
}

