/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepStatus } from './StepStatus';
import {
    StepStatusFromJSON,
    StepStatusFromJSONTyped,
    StepStatusToJSON,
    StepStatusToJSONTyped,
} from './StepStatus';

/**
 * Runtime status of one workflow step (the live progress view).
 * @export
 * @interface WorkflowStepState
 */
export interface WorkflowStepState {
    /**
     * The job executing this step, once one has been scheduled.
     * @type {string}
     * @memberof WorkflowStepState
     */
    job_id?: string | null;
    /**
     * The step's name (its address within the workflow).
     * @type {string}
     * @memberof WorkflowStepState
     */
    name: string;
    /**
     * 
     * @type {StepStatus}
     * @memberof WorkflowStepState
     */
    status: StepStatus;
}



/**
 * Check if a given object implements the WorkflowStepState interface.
 */
export function instanceOfWorkflowStepState(value: object): value is WorkflowStepState {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WorkflowStepStateFromJSON(json: any): WorkflowStepState {
    return WorkflowStepStateFromJSONTyped(json, false);
}

export function WorkflowStepStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStepState {
    if (json == null) {
        return json;
    }
    return {
        
        'job_id': json['job_id'] == null ? undefined : json['job_id'],
        'name': json['name'],
        'status': StepStatusFromJSON(json['status']),
    };
}

export function WorkflowStepStateToJSON(json: any): WorkflowStepState {
    return WorkflowStepStateToJSONTyped(json, false);
}

export function WorkflowStepStateToJSONTyped(value?: WorkflowStepState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['job_id'],
        'name': value['name'],
        'status': StepStatusToJSON(value['status']),
    };
}

