/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnSuccess } from './OnSuccess';
import {
    OnSuccessFromJSON,
    OnSuccessFromJSONTyped,
    OnSuccessToJSON,
    OnSuccessToJSONTyped,
} from './OnSuccess';
import type { JobConfig } from './JobConfig';
import {
    JobConfigFromJSON,
    JobConfigFromJSONTyped,
    JobConfigToJSON,
    JobConfigToJSONTyped,
} from './JobConfig';
import type { OnFailure } from './OnFailure';
import {
    OnFailureFromJSON,
    OnFailureFromJSONTyped,
    OnFailureToJSON,
    OnFailureToJSONTyped,
} from './OnFailure';

/**
 * A node in a workflow DAG. Steps are addressed by their unique `name`;
 * `depends_on` lists the names of steps that must complete first.
 * @export
 * @interface WorkflowStep
 */
export interface WorkflowStep {
    /**
     * 
     * @type {JobConfig}
     * @memberof WorkflowStep
     */
    config?: JobConfig | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowStep
     */
    depends_on?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowStep
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    name: string;
    /**
     * 
     * @type {OnFailure}
     * @memberof WorkflowStep
     */
    on_failure?: OnFailure;
    /**
     * 
     * @type {OnSuccess}
     * @memberof WorkflowStep
     */
    on_success?: OnSuccess;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowStep
     */
    payload?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    task_name: string;
}



/**
 * Check if a given object implements the WorkflowStep interface.
 */
export function instanceOfWorkflowStep(value: object): value is WorkflowStep {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('task_name' in value) || value['task_name'] === undefined) return false;
    return true;
}

export function WorkflowStepFromJSON(json: any): WorkflowStep {
    return WorkflowStepFromJSONTyped(json, false);
}

export function WorkflowStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStep {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : JobConfigFromJSON(json['config']),
        'depends_on': json['depends_on'] == null ? undefined : json['depends_on'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'on_failure': json['on_failure'] == null ? undefined : OnFailureFromJSON(json['on_failure']),
        'on_success': json['on_success'] == null ? undefined : OnSuccessFromJSON(json['on_success']),
        'payload': json['payload'] == null ? undefined : json['payload'],
        'task_name': json['task_name'],
    };
}

export function WorkflowStepToJSON(json: any): WorkflowStep {
    return WorkflowStepToJSONTyped(json, false);
}

export function WorkflowStepToJSONTyped(value?: WorkflowStep | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': JobConfigToJSON(value['config']),
        'depends_on': value['depends_on'],
        'metadata': value['metadata'],
        'name': value['name'],
        'on_failure': OnFailureToJSON(value['on_failure']),
        'on_success': OnSuccessToJSON(value['on_success']),
        'payload': value['payload'],
        'task_name': value['task_name'],
    };
}

