/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStep } from './WorkflowStep';
import {
    WorkflowStepFromJSON,
    WorkflowStepFromJSONTyped,
    WorkflowStepToJSON,
    WorkflowStepToJSONTyped,
} from './WorkflowStep';
import type { WorkflowStatus } from './WorkflowStatus';
import {
    WorkflowStatusFromJSON,
    WorkflowStatusFromJSONTyped,
    WorkflowStatusToJSON,
    WorkflowStatusToJSONTyped,
} from './WorkflowStatus';

/**
 * A workflow instance and its steps.
 * @export
 * @interface Workflow
 */
export interface Workflow {
    /**
     * 
     * @type {Date}
     * @memberof Workflow
     */
    completed_at?: Date | null;
    /**
     * Accumulated step results, keyed by step name. Passed to downstream steps
     * under the `_context` payload key.
     * @type {{ [key: string]: any; }}
     * @memberof Workflow
     */
    context?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof Workflow
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof Workflow
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Workflow
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof Workflow
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Workflow
     */
    started_at?: Date | null;
    /**
     * 
     * @type {WorkflowStatus}
     * @memberof Workflow
     */
    status: WorkflowStatus;
    /**
     * 
     * @type {Array<WorkflowStep>}
     * @memberof Workflow
     */
    steps: Array<WorkflowStep>;
    /**
     * 
     * @type {string}
     * @memberof Workflow
     */
    tenant_id?: string | null;
}



/**
 * Check if a given object implements the Workflow interface.
 */
export function instanceOfWorkflow(value: object): value is Workflow {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function WorkflowFromJSON(json: any): Workflow {
    return WorkflowFromJSONTyped(json, false);
}

export function WorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workflow {
    if (json == null) {
        return json;
    }
    return {
        
        'completed_at': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'context': json['context'] == null ? undefined : json['context'],
        'created_at': (new Date(json['created_at'])),
        'id': json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'started_at': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'status': WorkflowStatusFromJSON(json['status']),
        'steps': ((json['steps'] as Array<any>).map(WorkflowStepFromJSON)),
        'tenant_id': json['tenant_id'] == null ? undefined : json['tenant_id'],
    };
}

export function WorkflowToJSON(json: any): Workflow {
    return WorkflowToJSONTyped(json, false);
}

export function WorkflowToJSONTyped(value?: Workflow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed_at': value['completed_at'] == null ? undefined : ((value['completed_at'] as any).toISOString()),
        'context': value['context'],
        'created_at': ((value['created_at']).toISOString()),
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'started_at': value['started_at'] == null ? undefined : ((value['started_at'] as any).toISOString()),
        'status': WorkflowStatusToJSON(value['status']),
        'steps': ((value['steps'] as Array<any>).map(WorkflowStepToJSON)),
        'tenant_id': value['tenant_id'],
    };
}

