/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lifecycle state of a workflow instance.
 * @export
 */
export const WorkflowStatus = {
    Created: 'created',
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed',
    PartiallyFailed: 'partially_failed',
    Cancelled: 'cancelled'
} as const;
export type WorkflowStatus = typeof WorkflowStatus[keyof typeof WorkflowStatus];


export function instanceOfWorkflowStatus(value: any): boolean {
    for (const key in WorkflowStatus) {
        if (Object.prototype.hasOwnProperty.call(WorkflowStatus, key)) {
            if (WorkflowStatus[key as keyof typeof WorkflowStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkflowStatusFromJSON(json: any): WorkflowStatus {
    return WorkflowStatusFromJSONTyped(json, false);
}

export function WorkflowStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStatus {
    return json as WorkflowStatus;
}

export function WorkflowStatusToJSON(value?: WorkflowStatus | null): any {
    return value as any;
}

export function WorkflowStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkflowStatus {
    return value as WorkflowStatus;
}

