/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowDiagramResponse
 */
export interface WorkflowDiagramResponse {
    /**
     * The diagram document (Mermaid `graph TD`).
     * @type {string}
     * @memberof WorkflowDiagramResponse
     */
    diagram: string;
    /**
     * Diagram source format. Always `mermaid` today.
     * @type {string}
     * @memberof WorkflowDiagramResponse
     */
    format: string;
}

/**
 * Check if a given object implements the WorkflowDiagramResponse interface.
 */
export function instanceOfWorkflowDiagramResponse(value: object): value is WorkflowDiagramResponse {
    if (!('diagram' in value) || value['diagram'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function WorkflowDiagramResponseFromJSON(json: any): WorkflowDiagramResponse {
    return WorkflowDiagramResponseFromJSONTyped(json, false);
}

export function WorkflowDiagramResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowDiagramResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'diagram': json['diagram'],
        'format': json['format'],
    };
}

export function WorkflowDiagramResponseToJSON(json: any): WorkflowDiagramResponse {
    return WorkflowDiagramResponseToJSONTyped(json, false);
}

export function WorkflowDiagramResponseToJSONTyped(value?: WorkflowDiagramResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diagram': value['diagram'],
        'format': value['format'],
    };
}

