/* tslint:disable */
/* eslint-disable */
/**
 * QueueFlow API
 * REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStepState } from './WorkflowStepState';
import {
    WorkflowStepStateFromJSON,
    WorkflowStepStateFromJSONTyped,
    WorkflowStepStateToJSON,
    WorkflowStepStateToJSONTyped,
} from './WorkflowStepState';

/**
 * 
 * @export
 * @interface WorkflowStepStatesResponse
 */
export interface WorkflowStepStatesResponse {
    /**
     * One entry per step, in declaration order.
     * @type {Array<WorkflowStepState>}
     * @memberof WorkflowStepStatesResponse
     */
    steps: Array<WorkflowStepState>;
}

/**
 * Check if a given object implements the WorkflowStepStatesResponse interface.
 */
export function instanceOfWorkflowStepStatesResponse(value: object): value is WorkflowStepStatesResponse {
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function WorkflowStepStatesResponseFromJSON(json: any): WorkflowStepStatesResponse {
    return WorkflowStepStatesResponseFromJSONTyped(json, false);
}

export function WorkflowStepStatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStepStatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'steps': ((json['steps'] as Array<any>).map(WorkflowStepStateFromJSON)),
    };
}

export function WorkflowStepStatesResponseToJSON(json: any): WorkflowStepStatesResponse {
    return WorkflowStepStatesResponseToJSONTyped(json, false);
}

export function WorkflowStepStatesResponseToJSONTyped(value?: WorkflowStepStatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'steps': ((value['steps'] as Array<any>).map(WorkflowStepStateToJSON)),
    };
}

